version: "3.8"

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Comme spring.datasource.password est vide, laissez ce champ vide
      MYSQL_DATABASE: techmaster2
      MYSQL_USER: root
      MYSQL_PASSWORD: ""  # Comme spring.datasource.password est vide, laissez ce champ vide
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  spring-boot-app:
    depends_on:
      - mysql
    image: dhaouadi1515/gestion-de-rendezvous:latest
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
                 "spring.datasource.url"  : "jdbc:mysql://mysql:3306/techmaster2?createDatabaseIfNotExist=true",
                 "spring.datasource.username" : "root",
                 "spring.datasource.password" : "",
                 "spring.jpa.show-sql" : "true",
                 "spring.jpa.hibernate.ddl-auto" : "update",
                 "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
               }'
    ports:
      - "8084:8084"
    stdin_open: true
    tty: true

  angular-app:
    image: dhaouadi1515/gestion-de-rendezvous-angular:latest
    restart: on-failure
    ports:
      - "80:80"

volumes:
  db:
